### ISSUE TITLE
build on the windows, path is error 

### ISSUE THREAD

**Issue by inhere** [humbug/box#21]
exists path like: 'E:\workenv\php-docker.......'

![image](https://user-images.githubusercontent.com/5302062/35023938-f6b58abc-fb77-11e7-8a5f-1c0ab6a6147a.png)

Excuse me, how to clear there are path prefix?

**Comment by theofidry** [comment]
I apologize but for now there is no Windows support.

The issue is that:

- I know little of the Windows specificities
- I do not have a Windows machine to debug
- AppVeyor is not configure/enabled for the repository

I'll gladly accept help for the Windows support, but I really have enough in my hands so I won't be able to look into it.

**Comment by inhere** [comment]
Thank you for your reply

Reference composer PharCompiler class, and now I implemented a simple tool to package the application.

https://github.com/inhere/php-console/blob/master/src/Components/PharCompiler.php

**Comment by theofidry** [comment]
That's a nice idea and I think using Box for that would solve a few of your issues.

If you want windows support though I think setting up a service like [AppVeyor](https://www.appveyor.com/) (for both Box and your package) is required otherwise it's gonna be add to provide any guaranty

**Comment by theofidry** [comment]
This is unrelated to this issue but I recommend you to give a go to the new version of [Box](https://github.com/humbug/box) (there is an alpha release now) which should be significantly faster :)

**Comment by inhere** [comment]
Thank you for your suggestion 👍
