### ISSUE TITLE
Provide XZ compression

### ISSUE THREAD

**Issue by Majkl578** [humbug/box#211]
## Feature Request
XZ is by far the most efficient compresion format used by OSS, especially Debian where XZ is default for packaging.

https://en.wikipedia.org/wiki/Xz

**Comment by Majkl578** [comment]
There is issue for XZ support in general: https://bugs.php.net/bug.php?id=63880
You may want to create one for PHAR depending on this one.

Might be worth bringing this up in php.internals for 7.3?

**Comment by theofidry** [comment]
Thanks, I mentioned the PHARs in the thread. If mentioning it on PHP internals would help to give a bit of visibility to it that would be nice indeed

**Comment by theofidry** [comment]
Looks like there is a few more compression formats that could be used.

I'll be closing this issue for now since there is not much that can be done in Box until it lands in a PHP extension/core and I would like to keep the amount of open issues to its minimal. We should however open again this issue or a new issue whenever a new format lands.
