### ISSUE TITLE
Allow the "embed" SAPI

### ISSUE THREAD

**Issue by feamsr00** [humbug/box#332]
## Feature Request
Have the requirement checker allow the "embed" SAPI.

"embed"!==PHP_SAPI

Thanks!

**Comment by theofidry** [comment]
Hm actually I think I added this guard because of https://github.com/humbug/file_get_contents/pull/23, but this guard doesn't seem to be enough and I'm actually not sure if very useful here. After checking a couple of other projects, I only see Composer with [a similar guard](https://github.com/composer/composer/blob/master/bin/composer#L4).

Any recommendations @kelunik?

**Comment by theofidry** [comment]
I see. No harm adding it then :)
